# name: My workflow
# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: test
#         run: echo "test deploy"

name: Print Text from hellome.
on:
  push:
    branches:
      - main
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print text from file.txt
        run: cat a.html
      - name: Test
        run: |
          npm install
          npm run test
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo $deploy_url
          curl "$deploy_url"
